//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soft3dEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soft3dEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chessboard {
            get {
                object obj = ResourceManager.GetObject("chessboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monkey {
            get {
                object obj = ResourceManager.GetObject("monkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;autoClear&quot;:true,&quot;clearColor&quot;:[0.0000,0.0000,0.0000],&quot;ambientColor&quot;:[0.0000,0.0000,0.0000],&quot;gravity&quot;:[0.0000,-9.8100,0.0000],&quot;cameras&quot;:[{&quot;name&quot;:&quot;Camera&quot;,&quot;id&quot;:&quot;Camera&quot;,&quot;position&quot;:[7.4811,5.3437,-6.5076],&quot;target&quot;:[-0.3174,0.8953,0.3125],&quot;fov&quot;:0.8576,&quot;minZ&quot;:0.1000,&quot;maxZ&quot;:100.0000,&quot;speed&quot;:1.0000,&quot;inertia&quot;:0.9000,&quot;checkCollisions&quot;:false,&quot;applyGravity&quot;:false,&quot;ellipsoid&quot;:[0.2000,0.9000,0.2000]}],&quot;activeCamera&quot;:&quot;Camera&quot;,&quot;lights&quot;:[{&quot;name&quot;:&quot;Lamp&quot;,&quot;id&quot;:&quot;Lamp&quot;,&quot;type&quot;:0.0000,&quot;data&quot;:[4.0762,5.9039,1.0055],&quot;intensity&quot;:1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monkey1 {
            get {
                return ResourceManager.GetString("monkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sphere {
            get {
                object obj = ResourceManager.GetObject("sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
